// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyMYNraCD2ctypfhC8ASpb_C5luMANLBs',
    appId: '1:308378945973:web:b01c280ecd0258645731fc',
    messagingSenderId: '308378945973',
    projectId: 'greenkeyper-93416',
    authDomain: 'greenkeyper-93416.firebaseapp.com',
    storageBucket: 'greenkeyper-93416.firebasestorage.app',
    measurementId: 'G-NMPYN5NHG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPPIxICG5FBFLvvwAFRQ3L8HZAwMh3JP0',
    appId: '1:308378945973:android:eda3f37c17153c1a5731fc',
    messagingSenderId: '308378945973',
    projectId: 'greenkeyper-93416',
    storageBucket: 'greenkeyper-93416.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6yahrZbxg6F6ir02K2T2QqIoYbd_kgcg',
    appId: '1:308378945973:ios:31e59fd1f8ed416d5731fc',
    messagingSenderId: '308378945973',
    projectId: 'greenkeyper-93416',
    storageBucket: 'greenkeyper-93416.firebasestorage.app',
    iosBundleId: 'com.example.greenkeyperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6yahrZbxg6F6ir02K2T2QqIoYbd_kgcg',
    appId: '1:308378945973:ios:31e59fd1f8ed416d5731fc',
    messagingSenderId: '308378945973',
    projectId: 'greenkeyper-93416',
    storageBucket: 'greenkeyper-93416.firebasestorage.app',
    iosBundleId: 'com.example.greenkeyperApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyMYNraCD2ctypfhC8ASpb_C5luMANLBs',
    appId: '1:308378945973:web:351930a0f66740035731fc',
    messagingSenderId: '308378945973',
    projectId: 'greenkeyper-93416',
    authDomain: 'greenkeyper-93416.firebaseapp.com',
    storageBucket: 'greenkeyper-93416.firebasestorage.app',
    measurementId: 'G-CHJZJ976HS',
  );
}
